### ISSUE TITLE
46번 문제 질문

### ISSUE THREAD

**Issue by 2hyunbin** [onlybooks/python-algorithm-interview#149]
안녕하세요 책 잘 보고 있습니다. 읽다가 질문 드립니다.

46번 문제 405p 설명 그림 14-10 부분에서 리프노드 5 이후 None 까지 탐색하는 걸로 그려져 있는데 실제로는 트리 2에서 같은 위치의 값이 None이라서 풀이 대로라면 트리 1의 5만 탐색하고 끝날 것 같습니다. 그렇게 된다면 같은 예시에서 트리1 리프노드 5 이후에 추가 노드가 있을 경우 병합이 되지 않는 문제가 생길 거 같은데 맞게 이해한 걸까요?

책 속 풀이가 테스트 통과에는 문제가 없어서 제가 뭔가를 착각하고 있는지도 모르겠습니다. 의견 주시면 감사하겠습니다.

참조) 수정 풀이

```python
class Solution:
    def mergeTrees(self, root1: Optional[TreeNode], root2: Optional[TreeNode]) -> Optional[TreeNode]:
        if not root1 and not root2:
            return None

        node = TreeNode((root1.val if root1 else 0) + (root2.val if root2 else 0))
        node.left = self.mergeTrees(root1.left if root1 else None, root2.left if root2 else None)
        node.right = self.mergeTrees(root1.right if root1 else None, root2.right if root2 else None)
        
        return node

```

**Comment by likejazz** [comment]
early return으로 바꾸면서 분기 조건이 달라졌네요. 또한 매번 None 여부를 체크해야 해서 early return의 장점도 살리지 못하는 코드입니다. 좀 더 고민을 해보시면 좋겠습니다.

**Comment by IAMNOTAHUMANBEING** [comment]
아 else인 경우 값을 넣어 주는게 아니라 노드 자체 연결해주게 되는 거군요. 답변 감사드립니다.
